eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: currency-values-service
  profiles:
    active: ${PROFILE:local}

server:
  port: 8082