eureka:
  client:
    enabled: false

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME_TEST:jfundTestCurrencyValuesDB}
      password: ${DB_PASSWORD_TEST:float123}
      username: ${DB_USER_TEST:jfundAdmin}
      authentication-database: admin

app:
  scheduler:
    enabled: false
  kafka:
    server: ${KAFKA_SERVER:localhost:9092}
    currency-keys-topic: ${CURRENCY_KEYS_TOPIC:jfund-currency-keys}
    currency-values-topic: ${CURRENCY_VALUES_TOPIC:jfund-currency-values}
