spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:jfundLocalCurrencyValuesDB}
      password: ${DB_PASSWORD:float123}
      username: ${DB_USER:jfundAdmin}
      authentication-database: admin

app:
  scheduler:
    enabled: ${SCHEDULER_ENABLED:true}
    load-currency-values: ${LOAD_CURRENCY_VALUES_CRON:*/10 * * * * *}
    send-currency-values: ${SEND_CURRENCY_VALUES_CRON:*/10 * * * * *}
  kafka:
    server: ${KAFKA_SERVER:localhost:9092}
    currency-keys-topic: ${CURRENCY_KEYS_TOPIC:jfund-currency-keys}
    currency-values-topic: ${CURRENCY_VALUES_TOPIC:jfund-currency-values}