eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: currency-values-service
  profiles:
    active: ${PROFILE:dev}

server:
  port: 8082

app:
  kafka:
    currency-keys-topic:${CURRENCY-KEYS-TOPIC:jfund-currency-keys}